# Generated by Django 4.0.3 on 2022-03-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=200)),
                ('customerPhone', models.IntegerField(max_length=100)),
                ('customerAddress', models.CharField(max_length=300)),
            ],
        ),
    ]
